### ISSUE TITLE
Add the setup_version in the module.xml

### ISSUE THREAD

**Issue by RubenGV** [vs7/magento2-module-mediamanager#1]
![image](https://user-images.githubusercontent.com/17448350/110495929-494c1d80-80f5-11eb-8ff3-aa8e8f75fe5b.png)

Regards

**Comment by vs7** [comment]
Hi! Thank you for the issue report.
I suppose your Magento version is below 2.3 https://github.com/magento/magento2/issues/21382#issuecomment-465961175
Nevertheless i added the needed attribute to module.xml 
https://github.com/vs7/magento2-module-mediamanager/commit/088f94b740029dd668da798c89c9326a02416240
